Only one class label if only one class
beacon-biosignals/Lighthouse.jl pull request #80
Opened 2022-06-03 22:12 UTC by josephsdavid

2022-06-03 23:29 UTC, hannahilea requested changes
Tests are (correctly!) failing b/c this PR doesn't yet only set a single class for the various metrics rows! :) (Which is great, I'd be worried if the tests were passing right now.)

2022-06-03 23:29 UTC, hannahilea commented on Project.toml
> +version = "0.14.11"
On Monday, let's pick up our convo w/ @ericphanson about whether this should be a breaking release OR if we should bump the schema versions of `ClassRow`.

- [ ] Block merge on decision

2022-06-03 23:29 UTC, hannahilea commented on src/row.jl
> +        length(class_labels) == 1 || throw(ArgumentError("..."))
```suggestion
        length(class_labels) == 1 || throw(ArgumentError("Class labels should contain only single class label when `class_index` is not `multiclass`"))
```

2022-06-04 03:06 UTC, josephsdavid commented
> Tests are (correctly!) failing b/c this PR doesn't yet only set a single class for the various metrics rows! :) (Which is great, I'd be worried if the tests were passing right now.)

We are geniuses!

2026-01-07 18:02 UTC, closed without merging