Add non-normalized confusion matrix option
beacon-biosignals/Lighthouse.jl pull request #84
Opened 2022-06-30 01:25 UTC by hannahilea

Note that it doesn't yet get plotted by default anywhere, the default settings are the same.

2022-06-30 17:00 UTC, nbagherzadeh requested changes
LGTM! Two personal suggestions:

1) What are your thoughts on updating: 

`crange = (0.0, 1.0)` -> ` crange = (0.0, maximum([1.0, maximum(filter(!isnan,confusion))]))` 

so that for the non-normalized outputs, the cmap outputs are not all dark blue. (toy example: if you have a CM = [1, 0; 0, 100], you'd probably want the 100 to be darker than the 1). Adding maximum(1, maximum(args)) will ensure that the normalized figures look similar to previous version. 

test output: 
non-normalized:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/105268991/176735329-6296ef55-bf62-438e-b5c5-a956840abf55.png">
normalized:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/105268991/176735358-a3f10f6f-b71f-49e1-929f-c204769fc664.png">


2) plot_confusion_matrix! docstring (line 408), sounds like there are only two variants of the confusion matrix; however, we now have a non-normalized option.

2022-07-01 00:02 UTC, hannahilea commented
lol yep! great call. 😢 

<img width="231" alt="Screen Shot 2022-06-30 at 4 36 47 PM" src="https://user-images.githubusercontent.com/1076701/176796182-f76117de-f469-4f8f-82d4-d3405406be58.png">

2022-07-01 03:30 UTC, hannahilea commented
Fixed! Good catch :)
<img width="389" alt="Screen Shot 2022-06-30 at 8 30 25 PM" src="https://user-images.githubusercontent.com/1076701/176818004-4bc0b344-52f6-4161-95ba-b0946892978b.png">

2022-07-01 03:49 UTC, nbagherzadeh approved these changes
LGTM. Plots look great from test 👍 !

2022-07-01 03:49 UTC, nbagherzadeh commented on src/plotting.jl
> +    crange = isnothing(normalize_by) ? (0.0, maximum(filter(!isnan, confusion))) : (0.0, 1.0)
looks good :)

2022-07-01 05:07 UTC, merged